#!/bin/bash

DATE=`date '+%F.%T'`

run() {
  TOOL=$1
  IDENT=$2
  shift 2
  echo "Running: $TOOL ./cilk-parse demo/demo &> errors.$DATE.$IDENT"
  ../install/valgrind/bin/valgrind \
    --tool=$TOOL --suppressions=system.supp \
    --fair-sched=yes "$@" \
    ./cilk-parse ../install/dyninst/lib/libdw.so &> "errors.$DATE.$IDENT"
  ln -sf errors.$DATE.$IDENT errors.last.$IDENT
}

run helgrind hel
run drd drd
