#!/bin/bash

DATE=`date '+%F.%T'`
OUTPUTS=''

run() {
  TOOL=$1
  IDENT=$2
  shift 2
  echo "Running: $TOOL ./cilk-parse demo/demo &> errors.$DATE.$IDENT"
  ../../valgrind-3.14.0/vg-in-place \
    --tool=$TOOL --suppressions=ignoring.supp \
    --fair-sched=yes "$@" \
    ./cilk-parse demo/demo &> "errors.$DATE.$IDENT"
  OUTPUTS="$OUTPUTS errors.$DATE.$IDENT"
}

run helgrind hel
run drd drd
less $OUTPUTS
