#!/bin/bash
echo "running: cilkscreen ./cilk-parse ./cilk-parse > typescript.`date` 2>&1"
module load icc/2018.2.199-GCC-6.4.0
../pkgs/cilktools/bin/cilkscreen ./cilk-parse ./cilk-parse > "typescript.`date`" 2>&1 
